#!/usr/bin/env bash
# Check if the number of parameters is less than 3
if [ "$#" -lt 3 ]; then
  echo "Usage: $0 PATH_TO_FILE IP USERNAME [PATH_TO_SSH_KEY]"
  exit 1
fi

# Extract parameters
path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

# Set default path to SSH key if not provided
if [ -z "$path_to_ssh_key" ]; then
  path_to_ssh_key="$HOME/.ssh/id_rsa"
fi

# Transfer the file using scp
scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"

# Check if scp command was successful
if scp -q -r -i "$path_to_ssh_key" "$1" "$username@$ip:~/"; then
  echo "File transferred successfully!"
else
  echo "File transfer failed!"
fi
