#!/usr/bin/env bash
# Install nginx
apt-get -y update
apt-get install -y nginx

# Configure Nginx to listen on port 80
ufw allow 'Nginx HTTP'
#creating a page
echo "Hello World!" > /var/www/html/index.html
# Start Nginx
service nginx start
