#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Creating Sample Page
echo "Hello World!" > /var/www/html/index.html

# Modify the Nginx configuration
sudo sed -i '/server_name _;/a \\\n\tlocation /redirect_me {\n\t\treturn 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;\n\t}' /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
