#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page
class nginx {
  package { 'nginx':
    ensure => 'installed',
  }

  file { '/usr/share/nginx/html/404.html':
    ensure  => 'present',
    content => "<html><body><h1>404 Not Found</h1><p>Ceci n'est pas une page</p></body></html>",
  }

  file { '/etc/nginx/sites-available/default':
    ensure  => 'file',
    content => "
      server {
        listen 80 default_server;
        listen [::]:80 default_server;

        root /usr/share/nginx/html;
        index index.html index.htm;

        server_name _;

        error_page 404 /404.html;
        location = /404.html {
          internal;
        }
      }
    ",
    notify  => Exec['reload-nginx'],
  }

  service { 'nginx':
    ensure    => 'running',
    enable    => true,
    subscribe => File['/etc/nginx/sites-available/default'],
  }

  exec { 'reload-nginx':
    command     => 'service nginx reload',
    refreshonly => true,
  }
}

include nginx

