#!/usr/bin/env bash
# Configure Nginx server to have a custom 404 page

# Install nginx
sudo apt-get update
sudo apt-get install -y nginx

# Create a custom 404 page
sudo sh -c 'echo "Ceci n\'est pas une page." > /var/www/html/404.html'

# Modify the Nginx default configuration to use the custom 404 page
sudo sed -i 's/# server_names_hash_bucket_size 64;/server_names_hash_bucket_size 64;\n\n\terror_page 404 /404.html;\n\n\tlocation = /404.html {\n\t\tinternal;\n\t}/' /etc/nginx/sites-enabled/default

# Restart Nginx
sudo service nginx restart
