#!/usr/bin/env bash
#configure web-02 to be identical to web-01
sudo apt-get update
sudo apt-get install nginx -y
hostname = $(hostname)
sudo sed -i '/http {/a \        server_tokens off;\n        add_header X-Served-By $hostname;' /etc/nginx/nginx.conf
sudo systemctl restart nginx
