#!/usr/bin/env bash
# Transfer file using scp
# Check arguments
if [[ $# -lt 4 ]]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" -o stricthostkeychecking=no "$1" "$3@$2":~/
fi
