#!/usr/bin/env bash
#finding out what’s keeping your Ubuntu container’s Nginx installation from listening on port:80
sudo apt update
sudo apt install nginx
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx start
