#!/usr/bin/env bash
#management

PID_FILE=/var/run/my_process.pid
SCRIPT=manage_my_process

if [ -e $PID_FILE ]; then
  PID=$(cat $PID_FILE)
else
  PID=""
fi

start_process () {
  ./$SCRIPT &
  PID=$!
  echo $PID > $PID_FILE
  echo "$SCRIPT started"
}

stop_process () {
   if [ ! -z "$PID" ]; then
    kill $PID
    # Wait for process to stop
    sleep 1
    # Delete PID file
    rm $PID_FILE
    # Reset PID variable
    PID=""
    # Display message
    echo "$SCRIPT stopped"
  fi
}

restart_process () {
  stop_process
  start_process
  # Display message
  echo "$SCRIPT restarted"
}

# Check arguments
case "$1" in
  start)
    start_process
    ;;
  stop)
    stop_process
    ;;
  restart)
    restart_process
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
    ;;
esac

exit 0

