#!/usr/bin/env bash
# Get the PID of the 4-to_infinity_and_beyond process

pid=$(ps aux | grep '4-to_infinity_and_beyond' | grep -v grep | awk '{print $2}')
if [ -z "$pid" ]; then
  echo "4-to_infinity_and_beyond process is not running."
else
  kill "$pid"
  echo "4-to_infinity_and_beyond process stopped."
fi
