#!/usr/bin/env bash
# Find the PID of the 7-highlander process
pid=$(pgrep '7-highlander')

# Check if the process is running
if [ -z "$pid" ]; then
  echo "7-highlander process is not running."
else
  # Stop the process using pkill
  pkill '7-highlander'
  echo "7-highlander process stopped."
fi
