#!/usr/bin/env bash

echo "username user_id home_directory"
while read -r line; do
    username=$(echo "$line" | cut -d ':' -f 1)
    user_id=$(echo "$line" | cut -d ':' -f 3)
    home_directory=$(echo "$line" | cut -d ':' -f 6)
    echo "$username $user_id $home_directory"
done < /etc/passwd
