#!/usr/bin/env bash
# This script displays numbers from 1 to 20 and shows "bad luck from China", "bad luck from Japan", or "bad luck from Italy" depending on the iteration, using a while loop and case statement.

counter=1
while [ $counter -le 20 ]
do
  case $counter in
    4)
      echo "$counter and then bad luck from China"
      ;;
    9)
      echo "$counter and then bad luck from Japan"
      ;;
    17)
      echo "$counter and then bad luck from Italy"
      ;;
    *)
      echo $counter
      ;;
  esac
  ((counter++))
done
