#!/usr/bin/env bash
# Check if the script is run as root
sudo cp /etc/hosts /etc/hosts.bak
sudo sed -i 's/127.0.0.1/127.0.0.2/g' /etc/hosts
sudo sed -i 's/.*facebook.com/8.8.8.8 facebook.com/g' /etc/hosts
