#!/usr/bin/env bash

# Install Apache
sudo apt-get update
sudo apt-get install -y apache2

# Enable Apache rewrite module
sudo a2enmod rewrite

# Create a custom index.html file with "Hello Holberton"
echo "Hello Holberton" | sudo tee /var/www/html/index.html

# Restart Apache
sudo service apache2 restart
