#!/usr/bin/env bash
sed -i 's/user nginx;/user www-data;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/g' /etc/nginx/sites-available/default
service nginx restart
