#!/usr/bin/env bash
#script to connect to a server without typing a password
Host your_server
  HostName 54.145.241.156
  User ubuntu
  IdentityFile ~/.ssh/school
  PreferredAuthentications publickey
  PasswordAuthentication no
